### ISSUE TITLE
For searchFingerprint when err = ErrSearchRequestTooComplex the handlers will never get called

### ISSUE THREAD

**Issue by snowzach** [bradleypeabody/godap#3]
I follow what you were doing but if err = ErrSearchRequestTooComplex then it just returns and none of my handlers are ever called with a Search Fingerprint. Was there something else I was supposed to do to get it to call my handlers?

**Comment by bradleypeabody** [comment]
Gotcha.  Okay, I've gone ahead and removed that line for now - so your stuff should work against master now.

The overall issue that I'm concerned about here is that there isn't really standard for this search fingerprint.  I see the problem you are trying to solve but the solution seems brittle - multiple logically equivalent inputs can result in different fingerprints, and the fingerprint textual format doesn't match anything it's more or less just arbitrary.

You know, thinking about it more, it probably makes more sense to make a FingerprintSearch... struct and associated types and it can just be a different type of LDAPRequestHandler.  I think that is going to result in more maintainable code - because that way the "Simple..." version is just looking for a single attribute, and the fingerprint one can have it's own functionality that is just totally separate.

What do you think?

**Comment by snowzach** [comment]
Hmmm... Honestly it would be better to just have a search provider and figure out how to decode the search string so it just spits out the search string specified to ldapsearch. I'm sure it's not that complicated, just need to write a decoder.

**Comment by bradleypeabody** [comment]
Or possibly parse it into some sort of rudimentary AST so it's useful programmatically (i.e. after you reassemble it into an LDAP search string, what is the application going to do with it?  You can't parse LDAP (or [HTML](http://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags)) with regex :)

The approach I suggested above has as it's main benefit that it would be fast and simple to write and makes the specification of what each thing does exact.  Right now we're adding functionality to the "Simple..." implementation that less and less simple.  There is little cost to making another LDAPRequestHandler.  Although I realize there is a fair share of crufty ASN.1 decoding stuff happening in there - perhaps some of that can be pulled out into utility functions in order to make things cleaner.

**Comment by snowzach** [comment]
I think either method would be good at least for my use case. I essentially know what the query will look like that the application is making to LDAP, I just want to intercept it and answer the search with my own data. 

I wish I had more time to help out with it. This is a cool project.

As a side question, did you get TLS working? I saw some code but it wasn't clear to me how to leverage it. I'm still learning go.

**Comment by bradleypeabody** [comment]
Okay cool.  Yeah I think we'll leave it as-is for now, but it might get refactored later.

Yes, TLS is fairly easy to get working.  Something like:

```
ln, err := godap.LDAPListenTLS("127.0.0.1:10686", "path/to/cert", "path/to/key")
s := &LDAPServer{Listener:ln:Handlers:hs}
s.Serve()
```

This of course requires a [key and certificate](http://stackoverflow.com/questions/10175812/how-to-create-a-self-signed-certificate-with-openssl).

**Comment by snowzach** [comment]
Thanks!
